name: Run Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['22.x']
        os: [ubuntu-latest, macOS-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          clear: true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9
          run_install: true
        
      - name: Run lint
        run: pnpm lint

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['22.x']
        os: [ubuntu-latest, macOS-latest]
    steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
            clear: true

        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node }}

        - name: Install pnpm
          uses: pnpm/action-setup@v2
          with:
            version: 10
            run_install: true

        - name: Run tests
          run: pnpm test